services:
  - type: web
    name: bms-backend
    env: node
    plan: free
    buildCommand: npm install --production=false && npm install -g typescript && tsc
    startCommand: npm start
    healthCheckPath: /api/system/health
